# Generated by Django 5.1.2 on 2024-10-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_form',
            name='project_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='signup_form',
            name='email',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='project_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.CharField(max_length=10, null=True)),
                ('lat', models.CharField(max_length=10, null=True)),
                ('lid', models.CharField(max_length=10, null=True)),
                ('result', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_data', to='myapp.signup_form')),
            ],
        ),
    ]
