# Generated by Django 5.1.2 on 2024-10-29 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signup_form_project_name_alter_signup_form_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_form',
            name='data_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 29, 14, 38, 42, 728)),
        ),
        migrations.AddField(
            model_name='signup_form',
            name='face',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
