# Generated by Django 5.1.2 on 2024-10-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_signup_form_face_project_data_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_data',
            name='building_id',
            field=models.IntegerField(null=True),
        ),
    ]
